=== aleynadilan/edulog_API/target/test-classes/features/API/classess/classessJsonSchema/classessPost.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "isActive": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "level_key": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "integer"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "deletedAt": {
      "type": ["string", "null"],
      "format": "date-time"
    }
  },
  "required": ["isActive", "name", "id", "createdAt", "updatedAt"]
}

=== aleynadilan/edulog_API/target/test-classes/features/API/classess/classessJsonSchema/classessGet.json
[
  {
    "id": 32,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "12",
    "level_key": null
  },
  {
    "id": 31,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "12",
    "level_key": null
  },
  {
    "id": 22,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "4",
    "level_key": null
  },
  {
    "id": 36,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "11",
    "level_key": null
  },
  {
    "id": 50,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 15,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "0",
    "level_key": null
  },
  {
    "id": 53,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 58,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 30,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 39,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 35,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 57,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 26,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 19,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 46,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "10",
    "level_key": null
  },
  {
    "id": 27,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 54,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 29,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 59,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 48,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 52,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 55,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "10",
    "level_key": null
  },
  {
    "id": 40,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 41,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 51,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "5",
    "level_key": null
  },
  {
    "id": 44,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "2",
    "level_key": null
  },
  {
    "id": 42,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 43,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 45,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "10",
    "level_key": null
  },
  {
    "id": 38,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "11",
    "level_key": null
  },
  {
    "id": 25,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 24,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "9",
    "level_key": null
  },
  {
    "id": 28,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "1",
    "level_key": null
  },
  {
    "id": 21,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "10",
    "level_key": null
  },
  {
    "id": 12,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "11",
    "level_key": null
  },
  {
    "id": 14,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "0",
    "level_key": null
  },
  {
    "id": 20,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "0",
    "level_key": null
  },
  {
    "id": 37,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "12",
    "level_key": null
  },
  {
    "id": 47,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "12",
    "level_key": null
  },
  {
    "id": 17,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "12",
    "level_key": null
  },
  {
    "id": 67,
    "isActive": true,
    "createdAt": "2024-04-01T20:04:37.731Z",
    "updatedAt": "2024-04-01T20:04:37.731Z",
    "deletedAt": null,
    "name": "string",
    "level_key": null
  },
  {
    "id": 68,
    "isActive": true,
    "createdAt": "2024-04-02T12:28:51.936Z",
    "updatedAt": "2024-04-02T12:28:51.936Z",
    "deletedAt": null,
    "name": "string",
    "level_key": null
  },
  {
    "id": 2,
    "isActive": true,
    "createdAt": "2023-10-02T11:16:39.000Z",
    "updatedAt": "2024-02-06T19:04:41.601Z",
    "deletedAt": null,
    "name": "12",
    "level_key": "12"
  },
  {
    "id": 11,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "1",
    "level_key": "1"
  },
  {
    "id": 16,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "2",
    "level_key": "2"
  },
  {
    "id": 7,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "6",
    "level_key": "6"
  },
  {
    "id": 3,
    "isActive": true,
    "createdAt": "2023-12-18T12:38:01.978Z",
    "updatedAt": "2023-12-18T12:38:01.978Z",
    "deletedAt": null,
    "name": "0",
    "level_key": "0"
  },
  {
    "id": 1,
    "isActive": true,
    "createdAt": "2023-10-02T11:16:39.000Z",
    "updatedAt": "2023-10-02T11:16:39.000Z",
    "deletedAt": null,
    "name": "11",
    "level_key": "11"
  },
  {
    "id": 13,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "10",
    "level_key": "10"
  },
  {
    "id": 6,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
    "deletedAt": null,
    "name": "5",
    "level_key": "5"
  },
  {
    "id": 10,
    "isActive": true,
    "createdAt": "2023-12-23T06:23:56.124Z",
    "updatedAt": "2023-12-23T06:23:56.124Z",
